on:
  push:
    branches:
      - master
  pull_request:
    branches: '*'

name: Project build
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - uses: actions/checkout@master
        name: Checkout

      - name: Install dependencies
        run: |
          npm ci

      - name: Run build
        run: |
          npm run build
